export const screenNames = {
  signIn: 'SignIn',
  signUp: 'SignUp',
  homeStack: 'HomeStack',
  profileStack: 'ProfileStack',
  settingsStack: 'SettingsStack',
  getStarted: 'Get Started',
  productList: 'ProductList',
  productForm: 'ProductForm',
  fashion: 'Fashion',
  beauty: 'Beauty',
  productDetail: 'ProductDetail',
  chat: 'Chat',
  cart: 'Cart',
  profile: 'Profile',
  settings: 'Settings',
  notifications: 'Notifications',
  forgotPassword: 'Forgot Password',
} as const;
