export const screenNames = {
  signIn: 'Sign_In',
  signUp: 'Sign_Up',
  homeStack: 'Home_Stack',
  profileStack: 'Profile_Stack',
  settingsStack: 'Settings_Stack',
  getStarted: 'Get_Started',
  productList: 'Product_List',
  addProduct: 'Add_Product',
  fashion: 'Fashion',
  beauty: 'Beauty',
  search: 'Search',
  productDetail: 'Product_Detail',
  chat: 'Chat',
  cart: 'Cart',
  profile: 'Profile',
  settings: 'Settings',
  notifications: 'Notifications',
  forgotPassword: 'Forgot_Password',
} as const;
